import asyncio
import os
import shutil
import logging
from playwright.async_api import async_playwright

# Setup logging to see what is happening in the Render dashboard
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("recorder")

async def capture_signal_video(dashboard_url: str, selector: str, output_path: str):
    temp_video_dir = "/tmp/playwright_videos"
    os.makedirs(temp_video_dir, exist_ok=True)

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            args=["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage", "--disable-gpu"]
        )
        
        # We define the context and start recording
        context = await browser.new_context(
            viewport={"width": 1080, "height": 1920},
            record_video_dir=temp_video_dir
        )
        page = await context.new_page()

        try:
            logger.info(f"Navigating to {dashboard_url}...")
            await page.goto(dashboard_url, wait_until="domcontentloaded", timeout=45000)
            
            logger.info(f"Waiting for selector: {selector}")
            await page.wait_for_selector(selector, timeout=30000)
            
            logger.info("Selector found! Recording for 10 seconds...")
            await asyncio.sleep(10)
            logger.info("Recording complete.")
            
        except Exception as e:
            # THIS IS THE CRITICAL PART: 
            # If it fails, this will save an image so you can see why
            screenshot_path = "/tmp/error_debug.png"
            await page.screenshot(path=screenshot_path)
            logger.error(f"SCRIPT FAILED: {e}. Screenshot saved to {screenshot_path}")
            raise e
            
        finally:
            # Get the path of the video file that Playwright generated
            video_file = page.video.path() if page.video else None
            
            await context.close()
            await browser.close()

            # Only move the video if it exists
            if video_file and os.path.exists(video_file):
                shutil.move(video_file, output_path)
                logger.info(f"SUCCESS: Video moved to {output_path}")
            else:
                logger.error("FAILURE: No video file was generated by Playwright.")
